### Data Collection - TeamsÂ¶

---

In [1]:
import pandas as pd
from functools import reduce

from client.models.team import Team

from client.scrapers.whoscored.team import crawl_team_overall_stats, crawl_team_defensive_stats, crawl_team_offensive_stats

In [2]:
league_team_df = pd.read_csv('./league/Premier League.csv')

In [25]:
premier_league_df = pd.DataFrame(columns=[
           'team_name', 'total_games', 'goals', 'yellow', 'red',
           'ball_possession', 'pass_accuracy', 'aerial_duels_won_per_game',
           'rating', 'shots_allowed_per_game', 'tackles_per_game',
           'interceptions_per_game', 'fouls_conceded_per_game',
           'offsides_won_per_game', 'shots_per_game', 'shots_on_target_per_game',
           'dribbles_completed_per_game', 'fouls_won_per_game'
        ])
ucl_df = pd.DataFrame(columns=[
           'team_name', 'total_games', 'goals', 'yellow', 'red',
           'ball_possession', 'pass_accuracy', 'aerial_duels_won_per_game',
           'rating', 'shots_allowed_per_game', 'tackles_per_game',
           'interceptions_per_game', 'fouls_conceded_per_game',
           'offsides_won_per_game', 'shots_per_game', 'shots_on_target_per_game',
           'dribbles_completed_per_game', 'fouls_won_per_game'
        ])
for idx, row in league_team_df.iterrows():
    # excute player data crawling functions 
    overall_df = crawl_team_overall_stats(int(row.team_id))
    defensive_df = crawl_team_defensive_stats(int(row.team_id))
    offensive_df = crawl_team_offensive_stats(int(row.team_id))

    # merge dataframes
    team_df = reduce(lambda x,y: pd.merge(x,y, on='league_name', how='outer'), [overall_df, defensive_df, offensive_df])

    epl_row = team_df.loc[team_df['league_name'] == 'Premier League'].to_dict('records')
    if len(epl_row) > 0:
        epl_row[0]['team_name'] = row.team_name
        premier_league_df.loc[len(premier_league_df)] = epl_row[0]
        
    ucl_row = team_df.loc[team_df['league_name'] == 'Champions League'].to_dict('records')
    if len(ucl_row) > 0:
        ucl_row[0]['team_name'] = row.team_name
        ucl_df.loc[len(ucl_df)] = ucl_row[0]

In [26]:
premier_league_df

            team_name  ... fouls_won_per_game
0             Arsenal  ...               10.7
1         Aston Villa  ...               12.5
2         Bournemouth  ...               10.3
3           Brentford  ...               11.8
4            Brighton  ...               13.7
5             Burnley  ...               10.2
6             Chelsea  ...               11.6
7      Crystal Palace  ...               11.8
8             Everton  ...                8.9
9              Fulham  ...               10.3
10          Liverpool  ...               10.1
11              Luton  ...               10.1
12    Manchester City  ...               11.2
13  Manchester United  ...                9.3
14          Newcastle  ...               12.2
15  Nottingham Forest  ...                9.3
16   Sheffield United  ...                8.6
17          Tottenham  ...               14.8
18           West Ham  ...               10.4
19             Wolves  ...               11.3

[20 rows x 18 columns]

In [27]:
ucl_df

           team_name total_games  ... dribbles_completed_per_game fouls_won_per_game
0            Arsenal           4  ...                        10.3                8.8
1    Manchester City           4  ...                          12                 13
2  Manchester United           4  ...                         9.8                8.5
3          Newcastle           4  ...                         4.3                 13

[4 rows x 18 columns]